<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <WasmBuildNative>true</WasmBuildNative>
    <DefineConstants>$(DefineConstants);BROWSER</DefineConstants>
    <RootNamespace>SpaceShooter</RootNamespace>

    <!-- use nugets or ref drawnui source-->
    <UseSource>false</UseSource>

  </PropertyGroup>

  <!-- Shared game code -->
  <Import Project="../Shared/SpaceShooter.Shared.projitems" Label="Shared" />

  <ItemGroup Condition="'$(UseSource)' != 'true'">
    <PackageReference Include="DrawnUi.Blazor.Game" Version="1.10.0.1-preview1.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseSource)' == 'true'">
    <ProjectReference Include="..\..\..\DrawnUi\src\Blazor\Addons\DrawnUi.Blazor.Game\DrawnUi.Blazor.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="SkiaSharp" />
  </ItemGroup>

</Project>
